language: csharp

dotnet: 2.1.402
matrix:
    include:
        - os: linux # Ubuntu 14.04
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode7.2
        - os: osx
          osx_image: xcode9.4
        - os: osx
          osx_image: xcode10

script:
    - dotnet --info

    - dotnet restore
    - dotnet build
    - dotnet test uit.ooad.test
